#!/bin/bash
source "$EMUDECKGIT"/functions/checkPSBIOS.sh
source "$EMUDECKGIT"/functions/configEmuFP.sh
source "$EMUDECKGIT"/functions/configESDE.sh
source "$EMUDECKGIT"/functions/createDesktopIcons.sh
source "$EMUDECKGIT"/functions/createSaveFolders.sh
source "$EMUDECKGIT"/functions/installCHD.sh
source "$EMUDECKGIT"/functions/installEmuFP.sh
source "$EMUDECKGIT"/functions/installESDE.sh
source "$EMUDECKGIT"/functions/installPowerTools.sh
source "$EMUDECKGIT"/functions/installSRM.sh
source "$EMUDECKGIT"/functions/RAAchievment.sh
source "$EMUDECKGIT"/functions/RAautoSave.sh
source "$EMUDECKGIT"/functions/RABezels.sh
source "$EMUDECKGIT"/functions/RACores.sh
source "$EMUDECKGIT"/functions/RASNES.sh
source "$EMUDECKGIT"/functions/setESDEEmus.sh
source "$EMUDECKGIT"/functions/setMSG.sh
source "$EMUDECKGIT"/functions/setUpHolo.sh
source "$EMUDECKGIT"/functions/setWide.sh
source "$EMUDECKGIT"/functions/testLocationValid.sh