---
initial-setup: false
gdbstub: false
log-active-shaders: false
log-uniforms: false
log-compat-warn: false
validation-layer: true
pstv-mode: false
show-mode: false
demo-mode: false
apps-list-grid: false
stretch_the_display_area: false
fullscreen_hd_res_pixel_perfect: false
archive-log: false
backend-renderer: Vulkan
custom-driver-name: ''
turbo-mode: false
gpu-idx: 0
high-accuracy: false
resolution-multiplier: 1
disable-surface-sync: true
screen-filter: Bilinear
v-sync: true
anisotropic-filtering: 1
texture-cache: true
async-pipeline-compilation: true
show-compile-shaders: true
hashless-texture-cache: false
import-textures: false
export-textures: false
export-as-png: true
memory-mapping: double-buffer
boot-apps-full-screen: false
show-live-area-screen: false
audio-backend: SDL
audio-volume: 100
ngs-enable: true
sys-button: 1
sys-lang: 1
sys-date-format: 2
sys-time-format: 0
cpu-pool-size: 10
modules-mode: 0
delay-background: 4
delay-start: 30
background-alpha: 0.3
log-level: 0
cpu-opt: true
pref-path: $storagePath/Vita3K/
discord-rich-presence: true
wait-for-debugger: false
color-surface-debug: false
performance-overlay: false
performance-overlay-detail: 0
performance-overlay-position: 0
screenshot-format: 1
disable-motion: false
controller-analog-multiplier: 1
keyboard-button-select: ShiftRight
keyboard-button-start: Enter
keyboard-button-up: ArrowUp
keyboard-button-right: ArrowRight
keyboard-button-down: ArrowDown
keyboard-button-left: ArrowLeft
keyboard-button-l1: KeyQ
keyboard-button-r1: KeyE
keyboard-button-l2: KeyU
keyboard-button-r2: KeyO
keyboard-button-l3: KeyF
keyboard-button-r3: KeyH
keyboard-button-triangle: KeyV
keyboard-button-circle: KeyC
keyboard-button-cross: KeyX
keyboard-button-square: KeyZ
keyboard-leftstick-left: KeyA
keyboard-leftstick-right: KeyD
keyboard-leftstick-up: KeyW
keyboard-leftstick-down: KeyS
keyboard-rightstick-left: KeyJ
keyboard-rightstick-right: KeyL
keyboard-rightstick-up: KeyI
keyboard-rightstick-down: KeyK
keyboard-button-psbutton: KeyP
keyboard-gui-fullscreen: F11
keyboard-gui-toggle-touch: KeyT
keyboard-toggle-texture-replacement: Unbound
keyboard-take-screenshot: Unbound
keyboard-pinch-modifier: Unbound
keyboard-alternate-pinch-in: Unbound
keyboard-alternate-pinch-out: Unbound
keyboard-button-select-alt: Unbound
keyboard-button-start-alt: Unbound
keyboard-button-up-alt: Unbound
keyboard-button-right-alt: Unbound
keyboard-button-down-alt: Unbound
keyboard-button-left-alt: Unbound
keyboard-button-l1-alt: Unbound
keyboard-button-r1-alt: Unbound
keyboard-button-l2-alt: Unbound
keyboard-button-r2-alt: Unbound
keyboard-button-l3-alt: Unbound
keyboard-button-r3-alt: Unbound
keyboard-button-triangle-alt: Unbound
keyboard-button-circle-alt: Unbound
keyboard-button-cross-alt: Unbound
keyboard-button-square-alt: Unbound
keyboard-leftstick-left-alt: Unbound
keyboard-leftstick-right-alt: Unbound
keyboard-leftstick-up-alt: Unbound
keyboard-leftstick-down-alt: Unbound
keyboard-rightstick-left-alt: Unbound
keyboard-rightstick-right-alt: Unbound
keyboard-rightstick-up-alt: Unbound
keyboard-rightstick-down-alt: Unbound
keyboard-button-psbutton-alt: Unbound
keyboard-gui-fullscreen-alt: Unbound
keyboard-gui-toggle-touch-alt: Unbound
keyboard-toggle-texture-replacement-alt: Unbound
keyboard-take-screenshot-alt: Unbound
keyboard-pinch-modifier-alt: Unbound
keyboard-alternate-pinch-in-alt: Unbound
keyboard-alternate-pinch-out-alt: Unbound
user-id: 00
user-auto-connect: false
user-lang: ''
show-welcome: true
warn-missing-firmware: true
check-for-updates-mode: 1
file-loading-delay: 0
shader-cache: true
spirv-shader: false
fps-hack: false
current-ime-lang: 4
psn-signed-in: 0
http-enable: true
http-timeout-attempts: 50
http-timeout-sleep-ms: 100
http-read-end-attempts: 10
http-read-end-sleep-ms: 250
adhoc-addr: 0
front-camera-type: 2
front-camera-id: ''
front-camera-image: ''
front-camera-color: 0
back-camera-type: 2
back-camera-id: ''
back-camera-image: ''
back-camera-color: 0
tracy-primitive-impl: false
controller-binds:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
controller-axis-binds:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
controller-led-color: []
lle-modules: []
ime-langs:
  - 4
tracy-advanced-profiling-modules: []
...
