---
initial-setup: true
gdbstub: false
log-active-shaders: false
log-uniforms: false
pstv-mode: false
show-gui: false
show-info-bar: false
apps-list-grid: true
show-live-area-screen: true
icon-size: 71
archive-log: false
backend-renderer: OpenGL
gpu-idx: 0
resolution-multiplier: 1
disable-surface-sync: false
enable-fxaa: false
v-sync: true
anisotropic-filtering: 1
texture-cache: true
hashless-texture-cache: false
boot-apps-full-screen: false
ngs-enable: true
sys-button: 1
sys-lang: 1
sys-date-format: 2
sys-time-format: 0
cpu-pool-size: 10
modules-mode: 0
delay-background: 4
delay-start: 10
background-alpha: 0.300000012
log-level: 0
cpu-backend: Dynarmic
cpu-opt: true
pref-path: /run/media/mmcblk0p1/Emulation/storage/Vita3K/
discord-rich-presence: true
wait-for-debugger: false
color-surface-debug: false
performance-overlay: false
perfomance-overlay-detail: 0
perfomance-overlay-position: 0
keyboard-button-select: 229
keyboard-button-start: 40
keyboard-button-up: 82
keyboard-button-right: 79
keyboard-button-down: 81
keyboard-button-left: 80
keyboard-button-l1: 20
keyboard-button-r1: 8
keyboard-button-l2: 24
keyboard-button-r2: 27
keyboard-button-l3: 9
keyboard-button-r3: 11
keyboard-button-triangle: 25
keyboard-button-circle: 6
keyboard-button-cross: 27
keyboard-button-square: 29
keyboard-leftstick-left: 4
keyboard-leftstick-right: 7
keyboard-leftstick-up: 26
keyboard-leftstick-down: 22
keyboard-rightstick-left: 13
keyboard-rightstick-right: 15
keyboard-rightstick-up: 12
keyboard-rightstick-down: 14
keyboard-button-psbutton: 19
user-id: ""
user-auto-connect: false
dump-textures: false
show-welcome: true
asia-font-support: false
shader-cache: true
spirv-shader: false
current-ime-lang: 4
tracy-primitive-impl: false
lle-modules:
  []
ime-langs:
  - 4
tracy-advanced-profiling-modules:
  []
...
