#!/bin/bash
cemu_exe="$(realpath "$(dirname "$0")/Cemu.exe")"
cemu_bottle='cemu'
args=("$@")
i=0
for a in "${args[@]}"
do
    if [[ "${a}" == "-g" ]] && [[ $((i+1)) -lt ${#args[@]} ]]
    then
        na="${args[$((i+1))]}"
        if ! [[ "$na" =~ ^[a-zA-Z]:\\ ]]
        then
            # we transform the unix path to the equivalent windows path
            na="$(realpath "$na")"
            na="Z:${na//\//\\}"
            args[$((i+1))]="$na"
        fi
    fi
    i=$((i+1))
done
exec flatpak run --command="bottles-cli" com.usebottles.bottles run \
    -b "$cemu_bottle" \
    -e "$cemu_exe" \
    -a "${args[*]@Q}"
