Player 1 Input:
  Handler: Evdev
  Device: Microsoft X-Box 360 pad 0
  Config:
    Left Stick Left: LX-
    Left Stick Down: LY+
    Left Stick Right: LX+
    Left Stick Up: LY-
    Right Stick Left: RX-
    Right Stick Down: RY+
    Right Stick Right: RX+
    Right Stick Up: RY-
    Start: Start
    Select: Select
    PS Button: Mode
    Square: X
    Cross: A
    Circle: B
    Triangle: Y
    Left: Hat0 X-
    Down: Hat0 Y+
    Right: Hat0 X+
    Up: Hat0 Y-
    R1: TR
    R2: RZ+
    R3: Thumb R
    L1: TL
    L2: LZ+
    L3: Thumb L
    Motion Sensor X:
      Axis: X
      Mirrored: false
      Shift: 0
    Motion Sensor Y:
      Axis: Y
      Mirrored: false
      Shift: 0
    Motion Sensor Z:
      Axis: Z
      Mirrored: false
      Shift: 0
    Motion Sensor G:
      Axis: RX
      Mirrored: false
      Shift: 0
    Pressure Intensity Button: ""
    Pressure Intensity Percent: 50
    Left Stick Multiplier: 100
    Right Stick Multiplier: 100
    Left Stick Deadzone: 30
    Right Stick Deadzone: 30
    Left Trigger Threshold: 0
    Right Trigger Threshold: 0
    Left Pad Squircling Factor: 5000
    Right Pad Squircling Factor: 5000
    Color Value R: 0
    Color Value G: 0
    Color Value B: 20
    Blink LED when battery is below 20%: true
    Use LED as a battery indicator: false
    LED battery indicator brightness: 10
    Enable Large Vibration Motor: true
    Enable Small Vibration Motor: true
    Switch Vibration Motors: false
    Mouse Movement Mode: Relative
    Mouse Deadzone X Axis: 60
    Mouse Deadzone Y Axis: 60
    Mouse Acceleration X Axis: 200
    Mouse Acceleration Y Axis: 250
    Left Stick Lerp Factor: 100
    Right Stick Lerp Factor: 100
    Analog Button Lerp Factor: 100
    Trigger Lerp Factor: 100
    Device Class Type: 0
    Vendor ID: 1356
    Product ID: 616
  Buddy Device: "Null"
Player 2 Input:
  Handler: Evdev
  Device: Microsoft X-Box 360 pad 1
  Config:
    Left Stick Left: LX-
    Left Stick Down: LY+
    Left Stick Right: LX+
    Left Stick Up: LY-
    Right Stick Left: RX-
    Right Stick Down: RY+
    Right Stick Right: RX+
    Right Stick Up: RY-
    Start: Start
    Select: Select
    PS Button: Mode
    Square: X
    Cross: A
    Circle: B
    Triangle: Y
    Left: Hat0 X-
    Down: Hat0 Y+
    Right: Hat0 X+
    Up: Hat0 Y-
    R1: TR
    R2: RZ+
    R3: Thumb R
    L1: TL
    L2: LZ+
    L3: Thumb L
    Motion Sensor X:
      Axis: X
      Mirrored: false
      Shift: 0
    Motion Sensor Y:
      Axis: Y
      Mirrored: false
      Shift: 0
    Motion Sensor Z:
      Axis: Z
      Mirrored: false
      Shift: 0
    Motion Sensor G:
      Axis: RX
      Mirrored: false
      Shift: 0
    Pressure Intensity Button: ""
    Pressure Intensity Percent: 50
    Left Stick Multiplier: 100
    Right Stick Multiplier: 100
    Left Stick Deadzone: 30
    Right Stick Deadzone: 30
    Left Trigger Threshold: 0
    Right Trigger Threshold: 0
    Left Pad Squircling Factor: 5000
    Right Pad Squircling Factor: 5000
    Color Value R: 0
    Color Value G: 0
    Color Value B: 20
    Blink LED when battery is below 20%: true
    Use LED as a battery indicator: false
    LED battery indicator brightness: 10
    Enable Large Vibration Motor: true
    Enable Small Vibration Motor: true
    Switch Vibration Motors: false
    Mouse Movement Mode: Relative
    Mouse Deadzone X Axis: 60
    Mouse Deadzone Y Axis: 60
    Mouse Acceleration X Axis: 200
    Mouse Acceleration Y Axis: 250
    Left Stick Lerp Factor: 100
    Right Stick Lerp Factor: 100
    Analog Button Lerp Factor: 100
    Trigger Lerp Factor: 100
    Device Class Type: 0
    Vendor ID: 1356
    Product ID: 616
  Buddy Device: "Null"
Player 3 Input:
  Handler: Evdev
  Device: Microsoft X-Box 360 pad 2
  Config:
    Left Stick Left: LX-
    Left Stick Down: LY+
    Left Stick Right: LX+
    Left Stick Up: LY-
    Right Stick Left: RX-
    Right Stick Down: RY+
    Right Stick Right: RX+
    Right Stick Up: RY-
    Start: Start
    Select: Select
    PS Button: Mode
    Square: X
    Cross: A
    Circle: B
    Triangle: Y
    Left: Hat0 X-
    Down: Hat0 Y+
    Right: Hat0 X+
    Up: Hat0 Y-
    R1: TR
    R2: RZ+
    R3: Thumb R
    L1: TL
    L2: LZ+
    L3: Thumb L
    Motion Sensor X:
      Axis: X
      Mirrored: false
      Shift: 0
    Motion Sensor Y:
      Axis: Y
      Mirrored: false
      Shift: 0
    Motion Sensor Z:
      Axis: Z
      Mirrored: false
      Shift: 0
    Motion Sensor G:
      Axis: RX
      Mirrored: false
      Shift: 0
    Pressure Intensity Button: ""
    Pressure Intensity Percent: 50
    Left Stick Multiplier: 100
    Right Stick Multiplier: 100
    Left Stick Deadzone: 30
    Right Stick Deadzone: 30
    Left Trigger Threshold: 0
    Right Trigger Threshold: 0
    Left Pad Squircling Factor: 5000
    Right Pad Squircling Factor: 5000
    Color Value R: 0
    Color Value G: 0
    Color Value B: 20
    Blink LED when battery is below 20%: true
    Use LED as a battery indicator: false
    LED battery indicator brightness: 10
    Enable Large Vibration Motor: true
    Enable Small Vibration Motor: true
    Switch Vibration Motors: false
    Mouse Movement Mode: Relative
    Mouse Deadzone X Axis: 60
    Mouse Deadzone Y Axis: 60
    Mouse Acceleration X Axis: 200
    Mouse Acceleration Y Axis: 250
    Left Stick Lerp Factor: 100
    Right Stick Lerp Factor: 100
    Analog Button Lerp Factor: 100
    Trigger Lerp Factor: 100
    Device Class Type: 0
    Vendor ID: 1356
    Product ID: 616
  Buddy Device: "Null"
Player 4 Input:
  Handler: Evdev
  Device: Microsoft X-Box 360 pad 3
  Config:
    Left Stick Left: LX-
    Left Stick Down: LY+
    Left Stick Right: LX+
    Left Stick Up: LY-
    Right Stick Left: RX-
    Right Stick Down: RY+
    Right Stick Right: RX+
    Right Stick Up: RY-
    Start: Start
    Select: Select
    PS Button: Mode
    Square: X
    Cross: A
    Circle: B
    Triangle: Y
    Left: Hat0 X-
    Down: Hat0 Y+
    Right: Hat0 X+
    Up: Hat0 Y-
    R1: TR
    R2: RZ+
    R3: Thumb R
    L1: TL
    L2: LZ+
    L3: Thumb L
    Motion Sensor X:
      Axis: X
      Mirrored: false
      Shift: 0
    Motion Sensor Y:
      Axis: Y
      Mirrored: false
      Shift: 0
    Motion Sensor Z:
      Axis: Z
      Mirrored: false
      Shift: 0
    Motion Sensor G:
      Axis: RX
      Mirrored: false
      Shift: 0
    Pressure Intensity Button: ""
    Pressure Intensity Percent: 50
    Left Stick Multiplier: 100
    Right Stick Multiplier: 100
    Left Stick Deadzone: 30
    Right Stick Deadzone: 30
    Left Trigger Threshold: 0
    Right Trigger Threshold: 0
    Left Pad Squircling Factor: 5000
    Right Pad Squircling Factor: 5000
    Color Value R: 0
    Color Value G: 0
    Color Value B: 0
    Blink LED when battery is below 20%: true
    Use LED as a battery indicator: false
    LED battery indicator brightness: 50
    Enable Large Vibration Motor: true
    Enable Small Vibration Motor: true
    Switch Vibration Motors: false
    Mouse Movement Mode: Relative
    Mouse Deadzone X Axis: 60
    Mouse Deadzone Y Axis: 60
    Mouse Acceleration X Axis: 200
    Mouse Acceleration Y Axis: 250
    Left Stick Lerp Factor: 100
    Right Stick Lerp Factor: 100
    Analog Button Lerp Factor: 100
    Trigger Lerp Factor: 100
    Device Class Type: 0
    Vendor ID: 1356
    Product ID: 616
  Buddy Device: "Null"
Player 5 Input:
  Handler: "Null"
  Device: "Null"
  Config:
    Left Stick Left: ""
    Left Stick Down: ""
    Left Stick Right: ""
    Left Stick Up: ""
    Right Stick Left: ""
    Right Stick Down: ""
    Right Stick Right: ""
    Right Stick Up: ""
    Start: ""
    Select: ""
    PS Button: ""
    Square: ""
    Cross: ""
    Circle: ""
    Triangle: ""
    Left: ""
    Down: ""
    Right: ""
    Up: ""
    R1: ""
    R2: ""
    R3: ""
    L1: ""
    L2: ""
    L3: ""
    Motion Sensor X:
      Axis: ""
      Mirrored: false
      Shift: 0
    Motion Sensor Y:
      Axis: ""
      Mirrored: false
      Shift: 0
    Motion Sensor Z:
      Axis: ""
      Mirrored: false
      Shift: 0
    Motion Sensor G:
      Axis: ""
      Mirrored: false
      Shift: 0
    Pressure Intensity Button: ""
    Pressure Intensity Percent: 50
    Left Stick Multiplier: 100
    Right Stick Multiplier: 100
    Left Stick Deadzone: 0
    Right Stick Deadzone: 0
    Left Trigger Threshold: 0
    Right Trigger Threshold: 0
    Left Pad Squircling Factor: 0
    Right Pad Squircling Factor: 0
    Color Value R: 0
    Color Value G: 0
    Color Value B: 0
    Blink LED when battery is below 20%: true
    Use LED as a battery indicator: false
    LED battery indicator brightness: 50
    Enable Large Vibration Motor: true
    Enable Small Vibration Motor: true
    Switch Vibration Motors: false
    Mouse Movement Mode: Relative
    Mouse Deadzone X Axis: 60
    Mouse Deadzone Y Axis: 60
    Mouse Acceleration X Axis: 200
    Mouse Acceleration Y Axis: 250
    Left Stick Lerp Factor: 100
    Right Stick Lerp Factor: 100
    Analog Button Lerp Factor: 100
    Trigger Lerp Factor: 100
    Device Class Type: 0
    Vendor ID: 1356
    Product ID: 616
  Buddy Device: "Null"
Player 6 Input:
  Handler: "Null"
  Device: "Null"
  Config:
    Left Stick Left: ""
    Left Stick Down: ""
    Left Stick Right: ""
    Left Stick Up: ""
    Right Stick Left: ""
    Right Stick Down: ""
    Right Stick Right: ""
    Right Stick Up: ""
    Start: ""
    Select: ""
    PS Button: ""
    Square: ""
    Cross: ""
    Circle: ""
    Triangle: ""
    Left: ""
    Down: ""
    Right: ""
    Up: ""
    R1: ""
    R2: ""
    R3: ""
    L1: ""
    L2: ""
    L3: ""
    Motion Sensor X:
      Axis: ""
      Mirrored: false
      Shift: 0
    Motion Sensor Y:
      Axis: ""
      Mirrored: false
      Shift: 0
    Motion Sensor Z:
      Axis: ""
      Mirrored: false
      Shift: 0
    Motion Sensor G:
      Axis: ""
      Mirrored: false
      Shift: 0
    Pressure Intensity Button: ""
    Pressure Intensity Percent: 50
    Left Stick Multiplier: 100
    Right Stick Multiplier: 100
    Left Stick Deadzone: 0
    Right Stick Deadzone: 0
    Left Trigger Threshold: 0
    Right Trigger Threshold: 0
    Left Pad Squircling Factor: 0
    Right Pad Squircling Factor: 0
    Color Value R: 0
    Color Value G: 0
    Color Value B: 0
    Blink LED when battery is below 20%: true
    Use LED as a battery indicator: false
    LED battery indicator brightness: 50
    Enable Large Vibration Motor: true
    Enable Small Vibration Motor: true
    Switch Vibration Motors: false
    Mouse Movement Mode: Relative
    Mouse Deadzone X Axis: 60
    Mouse Deadzone Y Axis: 60
    Mouse Acceleration X Axis: 200
    Mouse Acceleration Y Axis: 250
    Left Stick Lerp Factor: 100
    Right Stick Lerp Factor: 100
    Analog Button Lerp Factor: 100
    Trigger Lerp Factor: 100
    Device Class Type: 0
    Vendor ID: 0
    Product ID: 0
  Buddy Device: "Null"
Player 7 Input:
  Handler: "Null"
  Device: "Null"
  Config:
    Left Stick Left: ""
    Left Stick Down: ""
    Left Stick Right: ""
    Left Stick Up: ""
    Right Stick Left: ""
    Right Stick Down: ""
    Right Stick Right: ""
    Right Stick Up: ""
    Start: ""
    Select: ""
    PS Button: ""
    Square: ""
    Cross: ""
    Circle: ""
    Triangle: ""
    Left: ""
    Down: ""
    Right: ""
    Up: ""
    R1: ""
    R2: ""
    R3: ""
    L1: ""
    L2: ""
    L3: ""
    Motion Sensor X:
      Axis: ""
      Mirrored: false
      Shift: 0
    Motion Sensor Y:
      Axis: ""
      Mirrored: false
      Shift: 0
    Motion Sensor Z:
      Axis: ""
      Mirrored: false
      Shift: 0
    Motion Sensor G:
      Axis: ""
      Mirrored: false
      Shift: 0
    Pressure Intensity Button: ""
    Pressure Intensity Percent: 50
    Left Stick Multiplier: 100
    Right Stick Multiplier: 100
    Left Stick Deadzone: 0
    Right Stick Deadzone: 0
    Left Trigger Threshold: 0
    Right Trigger Threshold: 0
    Left Pad Squircling Factor: 0
    Right Pad Squircling Factor: 0
    Color Value R: 0
    Color Value G: 0
    Color Value B: 0
    Blink LED when battery is below 20%: true
    Use LED as a battery indicator: false
    LED battery indicator brightness: 50
    Enable Large Vibration Motor: true
    Enable Small Vibration Motor: true
    Switch Vibration Motors: false
    Mouse Movement Mode: Relative
    Mouse Deadzone X Axis: 60
    Mouse Deadzone Y Axis: 60
    Mouse Acceleration X Axis: 200
    Mouse Acceleration Y Axis: 250
    Left Stick Lerp Factor: 100
    Right Stick Lerp Factor: 100
    Analog Button Lerp Factor: 100
    Trigger Lerp Factor: 100
    Device Class Type: 0
    Vendor ID: 0
    Product ID: 0
  Buddy Device: "Null"